import React from 'react';

const ServiceDetails = () => {
    return (
        <section className='container mx-auto my-20'>
            <div className='grid md:grid-cols-2 gap-10'>
                <h2 className='text-3xl md:text-9xl font-bold mt-3 col-span-2'>Civil Litigation</h2>
                <img className='' src="https://img.freepik.com/premium-photo/lawyer-judge-counselor-having-team-meeting-with-client-law-legal-services_28283-884.jpg?w=2000" alt="" />
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum facilis cumque ullam nihil similique, illo eligendi voluptate nostrum quidem rerum, doloremque ab error praesentium asperiores fuga itaque aliquam expedita. Alias quidem labore mollitia vel officiis porro sit commodi. Officiis totam nobis mollitia consequatur, repudiandae quos iste ea cupiditate, ipsum, quod explicabo? Eius inventore accusamus, repellat ratione ut laboriosam quia id. Officia, tenetur. Vel unde odit blanditiis illo aperiam asperiores voluptatem fugit magnam, mollitia, tempore fugiat repellat distinctio fuga totam culpa. Ratione doloremque, mollitia et natus laudantium totam beatae quisquam enim, accusamus sint, perferendis rerum cumque eius voluptates debitis! Consequatur a soluta animi ab, atque accusamus quas porro tempora veniam officia ex delectus voluptate laboriosam provident magnam voluptas unde praesentium expedita dolorem fugit ad natus aliquam tempore! Sint eos pariatur nulla asperiores in aliquid adipisci ut, labore nemo quidem nostrum nihil, quo aperiam culpa magni ex placeat incidunt enim illo! Suscipit aliquam, laboriosam animi reprehenderit facilis, repellendus harum velit possimus minus voluptatibus eius explicabo veritatis soluta illo non aperiam labore ipsum rerum fugit doloremque eos. Alias mollitia corporis voluptas non quod fugiat qui cumque odit aliquam necessitatibus soluta praesentium molestias enim unde quam aut nemo id quaerat quis atque aliquid, labore quidem explicabo sapiente. Commodi debitis cum assumenda, saepe magni totam ducimus voluptatum consequuntur corporis labore explicabo sapiente corrupti quae quia laudantium illo ut dolor incidunt atque. Laboriosam, ut at? Sit amet culpa dignissimos unde quos debitis atque repudiandae, tempore voluptas soluta dolorum eum ipsa eos error? Pariatur maiores unde magnam praesentium ipsa aliquam laboriosam quibusdam corporis, officia veniam consectetur esse, asperiores perspiciatis veritatis eum? Sunt nihil quasi placeat earum saepe. Sint est rem minima voluptas sapiente eveniet ex, quisquam quod illum harum quibusdam saepe tempore. Quisquam architecto illo, quod molestias quos quam officiis, repellendus adipisci molestiae corporis accusantium, quis similique.</p>
            </div>
        </section>
    );
};

export default ServiceDetails;